on:
  workflow_call:
    inputs:
      build-version:
        required: true
        type: string
      configuration:
        required: false
        type: string
        default: 'Release'
      output-folder:
        required: false
        type: string
        default: ${{ github.workspace }}/publish
  workflow_dispatch:    # Allow running the workflow manually from the GitHub UI

env:
  BUILD_VERSION: ${{ inputs.build-version && inputs.build-version || '0.0.0-ci.0' }}
  BUILD_CONFIG: ${{ inputs.configuration && inputs.configuration || 'Release'}}
  SOLUTION: 'NuGetWorkflow.sln'
  NuGetDirectory: ${{ inputs.output-folder && inputs.output-folder || format('{0}/publish', github.workspace) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: |
        dotnet restore $SOLUTION
        dotnet tool restore

    - name: Clean output directory
      run: |
        echo $NuGetDirectory/*
        rm -rf $NuGetDirectory/*

    - name: Build
      run: >-
        dotnet build $SOLUTION
        --configuration $BUILD_CONFIG
        -p:Version=$BUILD_VERSION
        --no-restore

    - name: Run tests
      run: >-
        dotnet test
        --configuration $BUILD_CONFIG
        --no-restore
        --no-build
        --verbosity normal
        --logger "GitHubActions;annotations.titleFormat=\$test;annotations.messageFormat=\$error"

    - name: Create NuGet package
      run: >-
        dotnet pack
        --configuration $BUILD_CONFIG
        --no-build
        --verbosity normal
        -p:Version=$BUILD_VERSION
        --output $NuGetDirectory

    # Validate metadata and content of the NuGet package
    # https://www.nuget.org/packages/Meziantou.Framework.NuGetPackageValidation.Tool#readme-body-tab
    # If some rules are not applicable, you can disable them
    # using the --excluded-rules or --excluded-rule-ids option
    - name: Validate package
      run: >-
        ls $NuGetDirectory/*.nupkg | xargs dotnet tool run meziantou.validate-nuget-package

    - name: Upload nupkg artifact
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        if-no-files-found: error
        retention-days: 7
        path: $NuGetDirectory/*.nupkg